### ISSUE TITLE
In files page, the buttons wrap

### ISSUE THREAD

**Issue by MyColorfulDays** [andreax79/airflow-code-editor#10]
The `.buttons` css width is not enough.
```shell
$ pip show airflow_code_editor
Name: airflow-code-editor
Version: 3.3.0
```
![image](https://user-images.githubusercontent.com/21351745/111984546-77464e80-8b46-11eb-9003-447c6851cd59.png)

**Comment by andreax79** [comment]
Fixed in 3.3.1
Thanks!
