### ISSUE TITLE
Unbale to access the code editor

### ISSUE THREAD

**Issue by imthiyas90** [andreax79/airflow-code-editor#12]
I have installed the code editor and git via ubuntu wsl on windows.
I have added my airflow conf file as follows,
[code_editor]
git_cmd = /usr/bin/git
git_default_args = -c color.ui=true
git_init_repo = False
root_directory = /home/imthi/airflow/dags
line_length = 88
string_normalization = False
mount_name = data
mount_path = /home/imthi/airflow/data
mount1_name = logs
mount1_path = /home/imthi/airflow/logs

While i am trying to launch it through UI, it says no such a file or directory found
![image](https://user-images.githubusercontent.com/33797502/113149047-960cab00-9200-11eb-98b9-34e92a00da99.png)

**Comment by andreax79** [comment]
Please check the airflow webserver log.
In case of permission error the airflow websers logs contains something like the following:
[2021-04-01 06:34,884] {code_editor_view.py:105} ERROR - [Errno 13] Permission denied: 'filename...'
Is the folder /home/imthi/airflow/dags readable by the airflow user?

**Comment by imthiyas90** [comment]
Thank you, after given right permission. I am getting fatel error on .git folder which exists
![image](https://user-images.githubusercontent.com/33797502/113288689-493ada00-92bd-11eb-8409-2a740acf42e2.png)

![image](https://user-images.githubusercontent.com/33797502/113288753-58ba2300-92bd-11eb-8fa0-5c2c3cd08820.png)

please let me know if i am missing something here

**Comment by andreax79** [comment]
Probably there was a problem creating the git repository. Please try to delete the .git folder (if empty). The code editor will recreate it.

**Comment by imthiyas90** [comment]
So do I need to do reinstall code editor after deleting .git folder or launching the code editor would be fine ?

**Comment by andreax79** [comment]
Launching the code editor would be fine.
