### ISSUE TITLE
Airflow 2.0 installation issue

### ISSUE THREAD

**Issue by kelvinyes** [andreax79/airflow-code-editor#13]
Currently trying to install airflow-code-editor plugin. I'm using docker-compose-CeleryExecutor.yml from puckel for Airflow 2.0. I cloned the airflow-code-editor repository into my plugins folder and added it into my requirements.txt as well. I'm getting these errors on the webserver. How can I go about fixing this so I can use the plugin? 

![image](https://user-images.githubusercontent.com/46099449/114019599-78a09800-9823-11eb-8373-85543e56dc73.png)

**Comment by andreax79** [comment]
You don't need to clone the repository into the plugin folder.
Please only add the plugin to the requirements.txt

**Comment by kelvinyes** [comment]
> You don't need to clone the repository into the plugin folder.
> Please only add the plugin to the requirements.txt

Hi, thank you very much for the fast reply. I tried this and the result is that nothing happens at all. I see in the logs that the module is installed, but it is not loaded in as a plugin. I also tried to reload only the webserver docker container afterwards, but that didn't work either.

**Comment by andreax79** [comment]
It seems correct for me. Could you please post here your docker configuration?

**Comment by kelvinyes** [comment]
Here is my Dockerfile. I noticed that when I download airflow-code-editor through my Dockerfile, I can see the DAG Code Editor in my Admin tab. However, when I click it, I get a screen that says "No such file or directory" and my webserver log shows a message saying "webserver_1  | [2021-04-09 21:05:36,270] {utils.py:187} ERROR - [Errno 2] No such file or directory: 'git'". 

`# VERSION 1.10.9
# AUTHOR: Matthieu "Puckel_" Roisil
# DESCRIPTION: Basic Airflow container
# BUILD: docker build --rm -t puckel/docker-airflow .
# SOURCE: https://github.com/puckel/docker-airflow

FROM python:3.8-slim-buster
LABEL maintainer="Puckel_"

# Never prompt the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

# Airflow
ARG AIRFLOW_VERSION=2.0.0
ARG AIRFLOW_USER_HOME=/usr/local/airflow
ARG AIRFLOW_DEPS=""
ARG PYTHON_DEPS=""
ENV AIRFLOW_HOME=${AIRFLOW_USER_HOME}

# Define en_US.
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8
ENV LC_MESSAGES en_US.UTF-8

# Disable noisy "Handling signal" log messages:
# ENV GUNICORN_CMD_ARGS --log-level WARNING

RUN set -ex \
    && buildDeps=' \
        freetds-dev \
        libkrb5-dev \
        libsasl2-dev \
        libssl-dev \
        libffi-dev \
        libpq-dev \
        git \
    ' \
    && apt-get update -yqq \
    && apt-get upgrade -yqq \
    && apt-get install -yqq --no-install-recommends \
        $buildDeps \
        freetds-bin \
        build-essential \
        default-libmysqlclient-dev \
        apt-utils \
        curl \
        rsync \
        netcat \
        locales \
    && sed -i 's/^# en_US.UTF-8 UTF-8$/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen \
    && update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 \
    && useradd -ms /bin/bash -d ${AIRFLOW_USER_HOME} airflow \
    && pip install -U pip setuptools wheel \
    && pip install pytz \
    && pip install pyOpenSSL \
    && pip install ndg-httpsclient \
    && pip install pyasn1 \
    && pip install apache-airflow[crypto,celery,postgres,hive,jdbc,mysql,ssh${AIRFLOW_DEPS:+,}${AIRFLOW_DEPS}]==${AIRFLOW_VERSION} \
    && pip install 'redis==3.2' \
    && pip install 'sqlalchemy<1.4.0' \
    && if [ -n "${PYTHON_DEPS}" ]; then pip install ${PYTHON_DEPS}; fi \
    && apt-get purge --auto-remove -yqq $buildDeps \
    && apt-get autoremove -yqq --purge \
    && apt-get clean \
    && rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base

COPY script/entrypoint.sh /entrypoint.sh
COPY config/airflow.cfg ${AIRFLOW_USER_HOME}/airflow.cfg

RUN chown -R airflow: ${AIRFLOW_USER_HOME}

EXPOSE 8080 5555 8793

USER airflow
WORKDIR ${AIRFLOW_USER_HOME}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["webserver"]`

**Comment by andreax79** [comment]
I tested the Dockerfile and it works fine with a small fix.
You need to create the dags folder and to install git.
My test is here https://github.com/andreax79/airflow-code-editor/tree/docker/docker/puckel

**Comment by kelvinyes** [comment]
Thank you. Your changes worked for me, primarily installing git and setting init git repo to True in airflow.cfg.
