### ISSUE TITLE
Permission Denied error when opening code editor

### ISSUE THREAD

**Issue by matwerber1** [andreax79/airflow-code-editor#2]
Hi, 

I'm running the Airflow webserver in a docker container and getting a `permission denied` popup window in the code editor UI upon opening that window:

<img width="1055" alt="screenshot1" src="https://user-images.githubusercontent.com/28939541/75715411-39982e80-5c82-11ea-8678-8b70ad785763.png">

Wondering if you can help me troubleshoot? I'm guessing it has something to do with the `airflow` user in the container not having permission to a folder used by the local git install, but not sure how to find out what exactly is being denied. 

Here is my Dockerfile: 

```
FROM puckel/docker-airflow:1.10.9

USER root

COPY airflow.cfg ./airflow.cfg
COPY /dags ./dags
COPY entrypoint.sh /entrypoint.sh
COPY requirements.txt /requirements.txt

# Add directory in which pip installs to PATH
ENV PATH="/usr/local/airflow/.local/bin:${PATH}"

# Install Git for airflow-code-editor:
RUN apt update
RUN apt install -y git

USER airflow

ENTRYPOINT ["/entrypoint.sh"]

# Just for documentation. Expose webserver, worker and flower respectively
EXPOSE 8080
EXPOSE 8793
EXPOSE 5555
```

The `entrpoint.sh` script is omitted for brevity, but just know that it calls `pip install` on `requirements.txt`, which contains only this dependency: 

```sh
# requirements.txt
airflow-code-editor==2.1.1
```

If I attach the running container interactively, I can successfully call `git` with the airflow user, so again - wondering if there's a directory created somewhere specific for airflow-code-editor (when I was the root user) that the airflow user does not have access to?

**Comment by matwerber1** [comment]
OK it was obvious, just missed it. As your docs say, the default is that airflow-code-editor creates an empty git repo in the `./dags` folder. Since this was created with root, the airflow user didn't have access. 

There's likely a better least-privileges way to address this, but solved it by adding this line to the Dockerfile: 

```
RUN chmod -R a+rw ./dags
```

**Comment by neilharia7** [comment]
Hi, I tried adding same but inside the Dockerfile of `puckel/docker-airflow` with the package dependency in `PYTHON_DEPS`

```
.
.
USER airflow
WORKDIR ${AIRFLOW_USER_HOME}

ENTRYPOINT ["/entrypoint.sh"]

RUN chmod a+rw ./

CMD ["webserver"]
```

but this didn't work for me. any idea why?
