### ISSUE TITLE
Not working with Ver 2.0.2

### ISSUE THREAD

**Issue by thuybt** [andreax79/airflow-code-editor#21]
I have set up airflow ver2.0.2 with airflow-code-editor but stuck in the issue: 
![image](https://user-images.githubusercontent.com/59462501/118383589-78b56400-b629-11eb-9c54-ff019c89fe3b.png)
also, the log said this while I am trying to install the module: 
![image](https://user-images.githubusercontent.com/59462501/118383607-a39fb800-b629-11eb-9eeb-4ed3433371a7.png)
Please help.
I am not using docker for this

**Comment by andreax79** [comment]
Hi,

Please check the apache requirements, e.g.
pip install apache-airflow==2.0.2  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.2/constraints-3.7.txt"

Airflow code editor must be installed with pip
pip install airflow-code-editor
not copying the code into the plugin folder

**Comment by thuybt** [comment]
My issues was removed since I downgrade airflow into version 2.0.1
