### ISSUE TITLE
Mixed Content exception

### ISSUE THREAD

**Issue by xiaohuangji** [andreax79/airflow-code-editor#28]
### Background:
I deployed airflow and airflow-code-editor behind a proxy that handles the SSL termination. 

### Description
When I go to code_editor home or click a folder under left navigator, the page tries to fetch data by calling
**https://mydomain.com/code_editor//tree/files?long=true**, but a 308 redirect returned with a location 
**http://mydomain.com/code_editor/tree/files?long=true**. The scheme changed from https to http, which resulted in a complaining from broswer with exception `Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.` and page could not load appropriately.

**Comment by andreax79** [comment]
Hi,

Which version?

**Comment by xiaohuangji** [comment]
latest

**Comment by DreadfullyDistinct** [comment]
same issue is observed with 5.1.2. 

Logs are like following:
`10.5.5.5 - - [25/Nov/2021:10:21:15 +0100] "GET /code_editor//tree/files/dags/folder?long=true HTTP/1.1" 308 363 "https://airflow.somedomain.com/code_editor/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"`

As a result of the redirect the right pane on the Code editor displays 'No data found for table' 

The left pane works fine and displayes the folders as the GET request for the short version of tree endpoint seems fine.
`
10.12.135.14 - - [25/Nov/2021:11:11:13 +0100] "GET /code_editor/tree/files/dags/folder HTTP/1.1" 200 93 "https://airflow.somedomain.com/code_editor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
`

**Comment by xiaohuangji** [comment]
I was able to fix the problem by telling proxy to pass X-Forwarded-* to upstream. Particularly X-Forwarded-proto. 
If you are using ingress-nginx, try to enable `use-forwarded-headers`. @DreadfullyDistinct 

Should not be the problem on airflow-code-editor end.  Closing now.

**Comment by DreadfullyDistinct** [comment]
Thanks @xiaohuangji ! I checked nginx configuration. My issue was apparently that I didnt set in airflow.cfg following parameter.

`enable_proxy_fix = True
`

Writing here for reference to others. For some reason the mixed content error on browser was only happening on 308 redirects with Code Editor and not on other Airflow URLs, but I am not the expert here, so cannot tell.
