### ISSUE TITLE
How does aws airflow simply introduce this plugin？

### ISSUE THREAD

**Issue by ClownfishYang** [andreax79/airflow-code-editor#49]
Hello, we are using aws airflow, but its dag file is stored in s3, we want to be able to directly manipulate the s3 file, do not know what adjustments need to be done?
Please help me, thanks.

**Comment by andreax79** [comment]
Hi, with the version 6.0.0 you can now edit files on S3.
You have to install "fs-s3fs" and add a configure the following environment variable
AIRFLOW__CODE_EDITOR__MOUNT="name=dags,path=s3://your_bucket"
