### ISSUE TITLE
Dag file editor with airflow in cluster mode, can i configure to write to worker pod?

### ISSUE THREAD

**Issue by noheroes** [andreax79/airflow-code-editor#56]
There is a way to configure airflow-code-editor to save files to dags folder in worker pod instead to dags forlde in webserver pod?

Thanks...

**Comment by noheroes** [comment]
Hi, reading deployment templates i could saw that if i activate dags.persistence.enabled dags a pvc is mounted in worker and webserver pods, with this can use airflow-code-editor without problems.
the only question i still have is, why in the webserver template is validated airflow version to mount the pvc?

**Comment by andreax79** [comment]
Hi, I don't understand completely your scenario because my Kubernetes knowledge is very limited.
Are you using this https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html configuration?
Could you please post the relevant part of your configuration?
