### ISSUE TITLE
working on gcp

### ISSUE THREAD

**Issue by nellooo** [andreax79/airflow-code-editor#60]
Hello, i ve installed the plugin via gpc console and after restarting the web server the module doesn't appear in admin menu.
anyone was able to make it working?
Thanks

**Comment by benzimegido** [comment]
Hey Nelloo ,
Try to manage Airflow Access Control and grant you an Admin role, see here for more info
https://cloud.google.com/composer/docs/composer-2/airflow-rbac 
https://cloud.google.com/composer/docs/composer-2/install-plugins#a_newly-uploaded_plugin_is_not_visible_in_airflow_ui
