### ISSUE TITLE
'file not found' error for JSON files

### ISSUE THREAD

**Issue by ciollid2** [andreax79/airflow-code-editor#61]
Hello,

I am experiencing a bug where I cannot open an existing .json file. This bug happens if I use the UI to create the json file from scratch and if I upload a file created using the JSON module from my local machine.  The file will continue to show up in the folder browser and I can manipulate it (move/rename). When clicking the json file, it opens a blank file editor with the message in the top left 'file not found'.

I have confirmed with my server admin that the file exists on the server with the contents I used when creating it. The file is also readable by a DAG. Strangely, I have been able to open the file once or twice successfully and view/edit the contents, but after a short period it will become un-openable.

Any help would be greatly appreciated

**Comment by andreax79** [comment]
Witch version of Airflow Code Editor and Airflow are you using?
If possible, please post the python log, thanks.

**Comment by ciollid2** [comment]
Sorry for the delayed response. We are on Python version 3.7.14 and the code editor version 5.2.2.
Where can I find the log?
Thanks

**Comment by andreax79** [comment]
Until version 7.0.1, the editor was affected by "random" bugs downloading JSON.
Please check if with the last version (7.1.0) the bug is resolved.

**Comment by ciollid2** [comment]
Thanks, I will report back once we get that update done.
