### ISSUE TITLE
DAG Serialization

### ISSUE THREAD

**Issue by dwolfeu** [andreax79/airflow-code-editor#63]
Since Airflow 2.0.0 [DAG Serialization](https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html) has been standard (and cannot be turned off). This seems to be a problem for `airflow-code-editor`, since the webserver no longer has access to the DAG files. Is there a way around this?

**Comment by andreax79** [comment]
I don't understand your problem.
"webserver no longer has access to the DAG files" => it depends on your configuration, the airflow-code-editor needs to read the dags from somewhere, generally the filesystem but it can also read from s3 and any supported [python filesystem2](https://docs.pyfilesystem.org/en/latest/) backend.

**Comment by dwolfeu** [comment]
Thank you for your quick reply! The DAGs are in the scheduler pod (specifically in the directory `/opt/airflow/dags/repo`), but not in the webserver pod. But I think I see a solution: If we mount a persistent volume to both the directory `/opt/airflow/dags/repo` on the scheduler pod and the directory `/opt/airflow/dags/repo` on the webserver pod (where `airflow-code-editor` looks for DAGs), then hopefully it should work.

**Comment by andreax79** [comment]
Kubernetes configuration added here https://github.com/andreax79/airflow-code-editor/tree/main/kubernetes

**Comment by dwolfeu** [comment]
Thank you responding to this and sorry for my slow reply. We want to try out the configuration that you wrote, but at the moment we don't have the capacity.
