### ISSUE TITLE
Plug-in broken after v2.7.0 update: No module ‘psslib’

### ISSUE THREAD

**Issue by chsanjeev** [andreax79/airflow-code-editor#69]
**Describe the bug**
Plug-in is broken after migrating to airflow v2.7.0. , Python 3.11.4.

**To Reproduce**
Steps to reproduce the behavior: install the plug-in on 2.7.0 

Error displayed the Airflow UI — “Broken plugin: [airflow_code_editor.airflow_code_editor] No module named ‘psslib’”

**Screenshots**

**Server (please complete the following information):**
 - Airflow Code Editor version: latest version
- Airflow version: 2.7.0
 - Environment: docker
 - OS: Centos 8

**Client(please complete the following information):**
 - Browser: all browsers

**Additional context**

**Comment by AndreyLisichenko** [comment]
Confirm this bug on Python 3.8.2, RedHat 7, all installed from pip

**Comment by andreax79** [comment]
Fixed in version 7.4.1

**Comment by chsanjeev** [comment]
@andreax79 and @AndreyLisichenko - thank you for fixing the dependencies. It is working now.
