### ISSUE TITLE
Compatibility with v2.0.0?

### ISSUE THREAD

**Issue by pat-s** [andreax79/airflow-code-editor#7]
I just installed the plugin (v2.4.0) on v2.0.0b2 and I see

```
Broken plugin: [airflow_code_editor.airflow_code_editor] No module named 'flask_admin' 
```

Is there already compatibility with v2.0?

**Comment by andreax79** [comment]
Not yet, work in progress...

**Comment by andreax79** [comment]
New version 3.0.0 released.
It is compatible with both Airflow 1.10.x and 2.0.x.

**Comment by pat-s** [comment]
That was quick!

I am getting "permission denied" errors

```
{utils.py:176} ERROR - [Errno 13] Permission denied: '/opt/airflow/dags/.gitignore'
```

I have the following permissions for the `dags` folder

```
drwxr-xr-x 2 airflow airflow 4096 Nov 18 21:26 airflow/dags/
```

Do you have an idea what might be wrong?

**Comment by andreax79** [comment]
Hi, please check if the dags folder already contains the .gitignore file.
Are you using Docker?

**Comment by pat-s** [comment]
>  please check if the dags folder already contains the .gitignore file.

no `.gitignore` there

> Are you using Docker?

yes

**Comment by pat-s** [comment]
The reason were different UID/GID values for user `airflow` on the host and within the container.
