### ISSUE TITLE
airflow-code-editor on Airflow Composer(GCP) doesn't detect composer folders - dag, data, log, etc.

### ISSUE THREAD

**Issue by benzimegido** [andreax79/airflow-code-editor#76]
**Describe the bug**
I'm working with Airflow Composer (GCP), I installed the airflow-code-editor PyPI library, and when I entered to the code editor, he did not detect the composer DAGS(GCS) and any GCS folder, I also tried to set the "root_directory" and "mount"s Config Options, and I also install fs-gcsfs.

**To Reproduce**
1. Go to Airflow composer Version: 2.6.3+composer -> admin -> Dags Code Editor
2. Composer folders/buckets not detected.

**Expected behavior**
To see all the Composer folders( DAGS, data, logs, etc...)

**Screenshots**
![image](https://github.com/andreax79/airflow-code-editor/assets/45328717/bbb54b84-ac93-44d3-aeaf-a948f12b0384)

**Server (please complete the following information):**
 - Airflow Code Editor version: 7.5.0
 - Airflow version: composer-2.5.1-airflow-2.6.3
 - Environment: GCP composer

**Client(please complete the following information):**
 - Browser chrome
 - Version 123.0.6312.58 (Official Build) (arm64)

**Comment by andreax79** [comment]
It's likely that you have a problem with the configuration.
Try the new version 7.6.0, which reports the underlying error message instead of the "no data for table" message.
Please note that the root directory must be a local folder.

**Comment by benzimegido** [comment]
Thanks for your replay,
I upgraded to the new version, and as you said, I got an informative error message:
<img width="500" alt="image" src="https://github.com/andreax79/airflow-code-editor/assets/45328717/c3962b4d-5696-4fd5-bc7d-a0136bb32656">
It looks like it related to your last comment;
_"Please note that the root directory must be a local folder."_
What do you mean by that?
I have configured the root folder as mentioned in the Composer GCS folder.
Can you guide me on how to configure that?
