### ISSUE TITLE
308 (blocked:mixed-content)

### ISSUE THREAD

**Issue by elguero6** [andreax79/airflow-code-editor#79]
**Describe the bug**
I'm unable to delete a dag. I get the following error

**To Reproduce**
1. Go to 
![image](https://github.com/andreax79/airflow-code-editor/assets/8837275/f2fd5f07-98d5-4051-8034-1c1e79a12174)
2. Click on Trash icon
![image](https://github.com/andreax79/airflow-code-editor/assets/8837275/809c078d-9073-494c-a85b-dca015f50602)
![image](https://github.com/andreax79/airflow-code-editor/assets/8837275/2053f450-dc39-4c84-b805-24ece1021fd7)
_From developer tools :_
![image](https://github.com/andreax79/airflow-code-editor/assets/8837275/944546ff-ec7a-4c62-9f82-7867717305f5)
![image](https://github.com/andreax79/airflow-code-editor/assets/8837275/3923cbe8-aa9c-4904-a32b-0dc72b228281)

From the server logs :
"DELETE /code_editor//files/date_example_dag.py HTTP/1.1" 308 359

**Server (please complete the following information):**
 - Airflow Code Editor version: 7.6.0
- Airflow version: 2.7.3
 - Environment: Kubernetes
 - 
**Client(please complete the following information):**
 - Browser : tested on Safari, Chrome, Edge

**Comment by andreax79** [comment]
Are you using https for serving Airflow?
Please post your relevant configurations.

**Comment by longpt233** [comment]
just downgrade airflow-code-editor==7.2.1 work for me
my version apache-airflow==2.6.1

**Comment by andreax79** [comment]
Probably fixed in v7.6.1, not sure without the relevant configurations.
