### ISSUE TITLE
[Feature] "New file" button

### ISSUE THREAD

**Issue by dolfinus** [andreax79/airflow-code-editor#8]
Hi.

Thank you for this package, it is really saved my day!

How about adding "New file" button?
Currently there is only one option to make new file - open the existing one and then use "Save as" button with entering new file location.
But sometimes there are no files in the dags folder. In case of completely new installation the only way to create first file is to to that using some external tool, like file manager or console.

IMHO this will be really useful feature.

**Comment by andreax79** [comment]
Hi.
Good idea!
It's an useful missing feature. I'll add it in the next releae.

**Comment by dolfinus** [comment]
Great, thank you!

**Comment by andreax79** [comment]
New file button added in version 3.2.0
