### ISSUE TITLE
File with spaces not supported in Git 

### ISSUE THREAD

**Issue by AZSJTinus** [andreax79/airflow-code-editor#80]
**Describe the bug**
File containing spaces appear with quotes (") in the Git Workspace view.
However these cannot be opened nor staged.

**To Reproduce**
1. Add file containing space
2. Navigate to Git Workspace
3. Click the file or try to stage it

**Expected behavior**
File to be opened of staged

**Screenshots**
When staging
![image](https://github.com/andreax79/airflow-code-editor/assets/161581636/585561a3-74d7-4eeb-9fd4-0e67740258c0)
When opening
![image](https://github.com/andreax79/airflow-code-editor/assets/161581636/fb47d502-5286-4ae9-b9ab-cfa21ca9f43b)

**Server (please complete the following information):**
 - Airflow Code Editor version: 7.6.0
- Airflow version: 2.9.1
 - Environment: pip install
 - OS: Ubuntu

**Client(please complete the following information):**
 - Browser Firefox (same error in Edge)

**Additional context**
Workaround: Use files without spaces

**Comment by andreax79** [comment]
Fixed in v7.6.1
