### ISSUE TITLE
Unable to load the plugin on a VM

### ISSUE THREAD

**Issue by m-lautr** [andreax79/airflow-code-editor#82]
I just installed the plugin in a linux vm and I get this error in the UI (same when launching the webserver)
I installed airflow in a venv inside my vm with the command :
 - pip install "apache-airflow[celery]==2.9.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.2/constraints-3.8.txt"
 and the plugin with pip install airflow-code-editor
<img width="951" alt="airflow_bug" src="https://github.com/andreax79/airflow-code-editor/assets/173280311/c7018a11-32ee-4ff0-95d6-7e0ed1b7985c">

do you have any ideas to fix that ?
Thanks in advance.

**Comment by andreax79** [comment]
I have performed the following test without encountering any issues:

```
python3.8 -m virtualenv .
source ./bin/activate
pip install "apache-airflow[celery]==2.9.2" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.2/constraints-3.8.txt"
pip install airflow-code-editor
airflow webserver
```

From your screenshot, it seems that you have a directory named 'airflow_code_editor' in /home/airflow/airflow/plugins/. Please try deleting this folder and then restart Airflow.
