### ISSUE TITLE
return in finally can swallow exceptions

### ISSUE THREAD

**Issue by iritkatriel** [andreax79/airflow-code-editor#91]
In [`execute_git_command`](https://github.com/andreax79/airflow-code-editor/blob/b6fc30171b50b3e7f4bfab098dde5294fa052211/airflow_code_editor/git.py#L131) there is a `return` statement in a `finally` block. The return would suppress any in-flight exception.

This means that any `BaseException` (including `KeyboardInterrupt`) from the `try` clause, as well as any exception raised from the `except` clauses, will be swallowed.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by andreax79** [comment]
Fixed, thanks
